/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/info-icon.gltf --transform 
Files: ./public/info-icon.gltf [2.73MB] > /Users/abi/Documents/abigail/studio sunne/studio sunne/studio sunne website/studio-sunne/info-icon-transformed.glb [170.23KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/info-icon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/info-icon-transformed.glb')
