/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/studio-sunne-icon.gltf --transform 
Files: ./public/studio-sunne-icon.gltf [4.35MB] > /Users/abi/Documents/abigail/studio sunne/studio sunne/studio sunne website/studio-sunne/studio-sunne-icon-transformed.glb [269.09KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/studio-sunne-icon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/studio-sunne-icon-transformed.glb')
